FROM ubuntu:22.04

RUN apt-get update \
    && apt-get install curl -y \
    && apt-get install -y locales \
    && locale-gen en_US.UTF-8

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash \
    && apt-get install -y nodejs

WORKDIR /project

COPY ./project .

CMD ["npm", "install"]
CMD ["npm", "run", "build"]
CMD ["npm", "run", "start"]