version: '3.5'
services:
  project:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./project:/project
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0